export const INITIAL_GET_TASKS = 'INITIAL_GET_TASKS';
export const SUCCESS_GET_TASKS = 'SUCCESS_GET_TASKS';
export const ERROR_GET_TASKS = 'ERROR_GET_TASKS';

export const INITIAL_ADD_TASK = 'INITIAL_ADD_TASK';
export const SUCCESS_ADD_TASK = 'SUCCESS_ADD_TASK';
export const ERROR_ADD_TASK = 'ERROR_ADD_TASK';

export const INITIAL_SELECT_TASK = 'INITIAL_SELECT_TASK';
export const SUCCESS_SELECT_TASK = 'SUCCESS_SELECT_TASK';
export const ERROR_SELECT_TASK = 'ERROR_SELECT_TASK';

export const INITIAL_UPDATE_TASK = 'INITIAL_UPDATE_TASK';
export const SUCCESS_UPDATE_TASK = 'SUCCESS_UPDATE_TASK';
export const ERROR_UPDATE_TASK = 'ERROR_UPDATE_TASK';

export const INITIAL_DELETE_TASK = 'INITIAL_DELETE_TASK';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR';

export const REMOVE_TASK_ERROR = 'REMOVE_TASK_ERROR';